---
ssl_client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDazCCAlOgAwIBAgIUYljhkvL+xf/chKarfBs4pEMzv5kwDQYJKoZIhvcNAQEL
  BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
  GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDA4MTQyMjAxMDRaFw0yNTA4
  MTQyMjAxMDRaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
  HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
  AQUAA4IBDwAwggEKAoIBAQCQ18q2zz53BYX2C9kHRV7+HKYu2qBuzsYNdRzh1K+7
  Ph1ruIXGYuhn+0i+j9fmAVs1P37b2uSuiapE3NFDsnoOdH+HSXzbV6BDUGu9/Y/Y
  VKFomWgFrwG1MNRiWSAys+1znClQxATX9naplE8RjrPYNChWD0n3EqtQxrqrQkRD
  Mbv32C/1bosQ5vCatWT6P4KLaSC6FbCARLbvt54Q5YWr3WxNTb2K8zGLcNN9l8Zu
  8ZaU+JNRSES1x18Xv0mAzxQyjHELh93ttdhzpkF4ezuc0oxzsjHPSoQIntqm4lc5
  Dwuyzr9gNkrRzF3lFnIHy4h1zsCYgSZNInYrsFLEU6YxAgMBAAGjUzBRMB0GA1Ud
  DgQWBBQcTYPF2x/40Jthe4ggJ/iYXz11rTAfBgNVHSMEGDAWgBQcTYPF2x/40Jth
  e4ggJ/iYXz11rTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAd
  Alj+3pcSNMrZXcMIB80caJnsakJKH/ioc/rcyC6is1R8Dx5u0sigrTU9luzwiYMK
  ak/fdKbZrj4pMO+q8nJBOyxuxh2g+cLpWz2DYJnvKCEnSF7XIpIwIj9fL+r1X8uE
  7NW1/kfzvysPzIMPzXZDRdTARh5EuRjeQrdeSAaw2ZbGTpE+CK/LLgGo5wZ6304L
  XXbDWGJ+SS9cL8LyWqrj3ESbLbcDnHhGv5XINcjf3IslcBm09vwCpvyIwmTtZqoO
  U5kNNm6/5Z0xjD9G6FgSbdvHQ+Sj8aQItvWsRZg3rWFSI+aLHR6tvJYYm+6ZhdE6
  ekt8SLj2HL/xyiTGunqK
  -----END CERTIFICATE-----
