---
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Set default policies
  ufw:
    rule: allow
    direction: incoming
    policy: deny

- name: Allow SSH
  ufw:
    rule: allow
    name: "OpenSSH"

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow specific ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ firewall_allowed_ports }}"
  when: firewall_allowed_ports is defined

- name: Enable UFW
  ufw:
    state: enabled
    policy: yes
