- name: Install Docker
  hosts: all
  roles:
    - docker

- name: Configure Marzban containers
  hosts: all
  roles:
    - marzban

- name: Create or update nodes on panel
  hosts: all
  gather_facts: yes
  roles:
    - node
